### ISSUE TITLE
Add empty screens for the character creation.

### ISSUE THREAD

**Issue by simeonkrastev** [simeonkrastev/maze-hunter#3]
Add the following screens and for now leave them empty:
Choose Name
Choose Guild
Choose Gender
Select Attributes
Randomize All

Each screen should have only a title and a "Back" option.
Each screen should behave properly in the menu.

**Comment by projectraya** [comment]
All options from the menu now have their own screen with the option "Back", which when clicked returns the user to the previous screen

**Comment by simeonkrastev** [comment]
Perfect. However, it's the team lead role to change the task status in the project plan.
